FROM node:14-alpine

WORKDIR /usr/src/notif-app

COPY ./package*.json ./
RUN npm install

COPY ./src/common ./src/common
COPY ./src/notif ./src/notif
RUN mkdir ./tmp && echo '{}' >> ./tmp/state.json

CMD [ "node", "src/notif/index.js" ]

