version: '3'

services:
  twsnotif_notif:
    build: ./docker/notif/
    volumes:
      - "./data/notif/log/:/var/log/notif-app/"
  twsnotif_api:
    build: ./docker/api/
    volumes:
      - "./data/api/log/:/var/log/api-app/"

