version: '3'

services:
  notif:
    build:
      context: .
      dockerfile: Dockerfile-notif
    env_file:
      - ./common/.env
      - ./notif/.env
    volumes:
      - "./node_modules:/usr/src/notif-app/node_modules"
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    env_file:
      - ./common/.env
      - ./api/.env
    ports:
      - "$PORT:8080"
    volumes:
      - "./node_modules:/usr/src/api-app/node_modules"

networks:
  notif_net:
    driver: bridge
  api_net:
    driver: bridge

